#!/bin/bash
check_default_shell_root() {
	if [ -z "${SHELL##*zsh*}" ] ;then
			echo "Default shell is zsh."
	else
		echo -n "Default shell is not zsh. Do you want to chsh -s \$(which zsh)? (y/n)"
		old_stty_cfg=$(stty -g)
		stty raw -echo
		answer=$( while ! head -c 1 | grep -i '[ny]' ;do true ;done )
		stty $old_stty_cfg && echo
		if echo "$answer" | grep -iq "^y" ;then
			chsh -s $(which zsh)
		else
			echo "Warning: Your configuration won't work properly. If you exec zsh, it'll exec tmux which will exec your default shell which isn't zsh."
		fi
	fi
}

install_tmux_plugin() {
    if [ ! -f ~/.tmux.conf ]; then
        echo "installing tmux plugin"
        git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
        tmux source ~/.tmux.conf
    else
        echo "tmux already plugin installed "
    if
}

check_default_shell() {
	if [ -z "${SHELL##*zsh*}" ] ;then
			echo "Default shell is zsh."
	else
        touch ~/.bash_profile
        if grep -Fxq "SHELL" ~/.bash_profile; then
            echo "SHELL in pash_profile"
        else
            echo "ADDING ZSH SHELL pash_profile"
            export SHELL=`which zsh`
            echo "export SHELL="$SHELL >> ~/.bash_profile
            echo "exec "$SHELL >> ~/.bash_profile
            touch ~/.profile
            echo "export SHELL="$SHELL >> ~/.profile
            echo "[ -z "$ZSH_VERSION" ] && exec $SHELL -l" >> ~/.profile #
        fi #
	fi #
} #




#check_default_shell
check_default_shell #

# backup old files
[ -f ~/.zshrc ] && mv ~/.zshrc ~/.zshrc.old
[ -f ~/.tmux.conf ] && mv ~/.tmux.conf ~/.tmux.conf.old
if [ ! -f ~/.config/nvim/init.vim ]; then
    mkdir -p ~/.config/nvim/
    touch ~/.config/nvim/init.vim
else
    mv ~/.config/nvim/init.vim ~/.config/nvim/init.vim.old
fi #

printf "source '$HOME/dotfiles/zsh/zshrc_manager.sh'" >> ~/.zshrc
printf "source-file $HOME/dotfiles/tmux/tmux.conf" >> ~/.tmux.conf
# only append to nvim config file,  
printf "so $HOME/dotfiles/nvim/init.vim" >> ~/.config/nvim/init.vim


# Install the Vim-plug Plugin ManagerPermalink
#curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    #https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#echo
#echo "Please log out and log back in for default shell to be initialized."



# tmux

