name: CI build Docker
# https://www.docker.com/blog/first-docker-github-action-is-here
# https://github.com/docker/build-push-action
# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows

# Trigger the workflow on push or pull request, but only for the master branch
on: push

jobs:
  build-dotfiles:
    name: build dots
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Build PL Docker
          # publish master/release
          uses: docker/build-push-action@v2
          with:
#            build-args: |
#              PYTHON_VERSION=${{ matrix.python_version }}
#              PYTORCH_VERSION=${{ matrix.pytorch_version }}
            file: Dockerfile
            push: false
          timeout-minutes: 50
